/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Control.AccesoAleatorio;
import Modelo.Libro;
import Modelo.ArbolBMas;
import java.io.File;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import Modelo.Libro;
import Modelo.LimitarCaracter;
import java.util.List;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;
import javax.swing.table.TableColumnModel;


/**
 *
 * @author usurio
 */
public class Arboles extends javax.swing.JFrame {

    static ArbolBMas Codigo;//creacion de los arboles para indexacion
    static ArbolBMas Autor;
    static ArbolBMas Titulo;
    static String Nodo;//para validar si ya se creo un arbol 
    public Arboles() {
        initComponents();
        cbBuqueda.addItem("Arbol por Codigo");
        cbBuqueda.addItem("Arbol por Titulo");
        cbBuqueda.addItem("Arbol por Autor");
        
        cbTipoArbolRango.addItem("Arbol por Codigo");
        cbTipoArbolRango.addItem("Arbol por Titulo");
        cbTipoArbolRango.addItem("Arbol por Autor");
                
        Nodo=txtValorNodo.getText();
        taArbolCodigo.setEditable(false);
        taArbolTitulo.setEditable(false);
        taArbolAutor.setEditable(false);
        tbSalidaClave.setEditable(false);
        taSalidaRango.setEditable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        taArbolCodigo = new javax.swing.JTextArea();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        taArbolTitulo = new javax.swing.JTextArea();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        taArbolAutor = new javax.swing.JTextArea();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtValorNodo = new javax.swing.JTextField();
        btnCrearArboles = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        cbBuqueda = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lbClaveArbol = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        tbClave = new javax.swing.JTextField();
        btBuscar = new javax.swing.JButton();
        tbSalidaClave = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        tbInicio = new javax.swing.JTextField();
        tbFinal = new javax.swing.JTextField();
        btnBuscarRango = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        taSalidaRango = new javax.swing.JTextArea();
        jLabel9 = new javax.swing.JLabel();
        cbTipoArbolRango = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Arbol por Codigo"));

        taArbolCodigo.setColumns(20);
        taArbolCodigo.setRows(5);
        jScrollPane1.setViewportView(taArbolCodigo);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 450, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 336, Short.MAX_VALUE)
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Arbol por Titulo"));

        taArbolTitulo.setColumns(20);
        taArbolTitulo.setRows(5);
        jScrollPane2.setViewportView(taArbolTitulo);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 540, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 336, Short.MAX_VALUE)
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Arbol por Autor"));

        taArbolAutor.setColumns(20);
        taArbolAutor.setRows(5);
        jScrollPane3.setViewportView(taArbolAutor);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 481, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 337, Short.MAX_VALUE)
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Ingrese Tamaño del nodo para el arbol y pulse en crear"));

        jLabel1.setText("Tamaño Nodo:");

        txtValorNodo.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtValorNodoFocusGained(evt);
            }
        });
        txtValorNodo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtValorNodoActionPerformed(evt);
            }
        });
        txtValorNodo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtValorNodoKeyTyped(evt);
            }
        });

        btnCrearArboles.setText("Crear Arboles");
        btnCrearArboles.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrearArbolesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(txtValorNodo, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnCrearArboles)
                .addContainerGap(336, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtValorNodo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCrearArboles))
                .addContainerGap(32, Short.MAX_VALUE))
        );

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder("Buscar libro en el arbol"));

        cbBuqueda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbBuquedaActionPerformed(evt);
            }
        });

        jLabel2.setText("Seleccione el arbol donde desa buscar:");

        jLabel3.setText("Ingrese el");

        lbClaveArbol.setText("codigo");

        jLabel4.setText("a buscar:");

        tbClave.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tbClaveFocusGained(evt);
            }
        });

        btBuscar.setText("Buscar");
        btBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btBuscarActionPerformed(evt);
            }
        });

        jLabel5.setText("Resultado:");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(147, 147, 147)
                .addComponent(btBuscar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cbBuqueda, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tbClave, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(lbClaveArbol)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel4))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(tbSalidaClave)
                                .addContainerGap())))))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbBuqueda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(lbClaveArbol)
                    .addComponent(jLabel4)
                    .addComponent(tbClave, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btBuscar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tbSalidaClave, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addContainerGap())
        );

        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder("Bucar un rango de libros en el arbol"));

        jLabel6.setText("Seleccione el arbol donde desea buscar:");

        jLabel7.setText("Ingrese la clave de inicio del rango:");

        jLabel8.setText("Ingrese la clave final del rango");

        tbInicio.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tbInicioFocusGained(evt);
            }
        });

        tbFinal.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tbFinalFocusGained(evt);
            }
        });

        btnBuscarRango.setText("Buscar");
        btnBuscarRango.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarRangoActionPerformed(evt);
            }
        });

        taSalidaRango.setColumns(20);
        taSalidaRango.setRows(5);
        jScrollPane4.setViewportView(taSalidaRango);

        jLabel9.setText("Resultado:");

        cbTipoArbolRango.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbTipoArbolRangoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel6Layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(18, 18, 18)
                                .addComponent(cbTipoArbolRango, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel6Layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(tbInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(tbFinal, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 832, Short.MAX_VALUE)))
                .addGap(18, 18, 18))
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(439, 439, 439)
                .addComponent(btnBuscarRango)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(cbTipoArbolRango, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8)
                    .addComponent(tbInicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tbFinal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnBuscarRango)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addGap(23, 23, 23))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtValorNodoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtValorNodoActionPerformed
        // TODO add your handling code here:
         //Salida.append(MemoriaI[pos]+"\n");
    }//GEN-LAST:event_txtValorNodoActionPerformed

    private void btnCrearArbolesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearArbolesActionPerformed
        // TODO add your handling code here:
        
        Nodo=txtValorNodo.getText();
        if(txtValorNodo.getText().isEmpty()) {//validacion si el texbox esta vacio
            JOptionPane.showMessageDialog(this, "¡No se ingreso tamaño del nodo!", "Advertencia", JOptionPane.WARNING_MESSAGE);
            return;
        } 
        if(((Integer.parseInt(txtValorNodo.getText()))<=2)|((Integer.parseInt(txtValorNodo.getText()))>=129))//validacion del el tamaño del nodo
        {
            JOptionPane.showMessageDialog(this, "¡Debe ingresar un Nodo con un Valor mayor a 3 y Menor a 128!", "Advertencia", JOptionPane.WARNING_MESSAGE);
            return;
        }
        int TamañoNodo=Integer.parseInt(txtValorNodo.getText());
        
        Codigo=new ArbolBMas(TamañoNodo);//asigancion de tamaño del nodo al arbol
        Autor=new ArbolBMas(TamañoNodo);
        Titulo=new ArbolBMas(TamañoNodo);
        
        
        try {
            AccesoAleatorio.crearFileLibro( new File("ArchivosCreados\\Libro.dat") );
            for(int i=1; i<AccesoAleatorio.getNumeroRegistros();i++){//recorrido de registros por medio de la clase acceso aleatorio
                Libro A=AccesoAleatorio.getLibro(i);//ubicacion del puntero por medio de la clase acceso aleatorio
                if(A.getEstado()==0)
                {
                    Codigo.insertar(A.getCodLibro() , A.Atributos());//indexacion de la clave junto al registro correspondiente
                    Autor.insertar(A.getAutor() , A.Atributos()); 
                    Titulo.insertar(A.getTitulo() , A.Atributos()); 
                }
            
            } 
            
        } catch(IOException e) {
            JOptionPane.showMessageDialog(this, "Error en la búsqueda de registros.", "Error", JOptionPane.ERROR_MESSAGE);
        }
        taArbolCodigo.setText(Codigo.toString());//metodo para la obtencion de una vista del arbol por niveles por medio de una Area de texto
        taArbolTitulo.setText(Titulo.toString());
        taArbolAutor.setText(Autor.toString());
        
    }//GEN-LAST:event_btnCrearArbolesActionPerformed

    private void btBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btBuscarActionPerformed
        // TODO add your handling code here:
        String Seleccionado=(String)cbBuqueda.getSelectedItem();
        if(Nodo.isEmpty())//validacion de que el nodo no este en estado null
        {
             JOptionPane.showMessageDialog(this, "¡Se debe crear los arboles primero!", "Advertencia", JOptionPane.WARNING_MESSAGE);
            return;
        }
        if(Seleccionado=="Arbol por Codigo")
        {
            String Salida=tbClave.getText();
            if(Salida.isEmpty()) {//validacion de que el texbox no este vacio
            JOptionPane.showMessageDialog(this, "¡No se ingreso clave de busqueda", "Advertencia", JOptionPane.WARNING_MESSAGE);
            return;
            }
            if(Salida.length()<5)
            {
            Salida=String.format("%-5s", Salida);//adecuacion al formato del registro
            }
             if((Codigo.Buscar(Salida))==(null))//validacion de de que la clave exista en el arbol por medio del metodo BUSCAR de la clase arbol
            {
                JOptionPane.showMessageDialog(this, "No existe la clave ingresada en el arbol de Codigos", "Información", JOptionPane.INFORMATION_MESSAGE);
                return;
            }
            else
            tbSalidaClave.setText((String)Codigo.Buscar(Salida));//devolucion del registro relacionado con la clave de busqueda por medio de BUSCAR de la clase arbol
        }
        if(Seleccionado=="Arbol por Autor")
        {
            String Salida=tbClave.getText();
            if(Salida.isEmpty()) {//validacion de que el texbox no este vacio
            JOptionPane.showMessageDialog(this, "¡No se ingreso clave de busqueda", "Advertencia", JOptionPane.WARNING_MESSAGE);
            return;
            }
            if(Salida.length()<30)
            {
            Salida=String.format("%-30s", Salida);
            }
             if((Autor .Buscar(Salida))==(null))//validacion de de que la clave exista en el arbol por medio del metodo BUSCAR de la clase arbol
            {
                JOptionPane.showMessageDialog(this, "No existe la clave ingresada en el arbol de Autores", "Información", JOptionPane.INFORMATION_MESSAGE);
                return;
            }
            else
            tbSalidaClave.setText((String)Autor.Buscar(Salida));//devolucion del registro relacionado con la clave de busqueda por medio de BUSCAR de la clase arbol
        }
        if(Seleccionado=="Arbol por Titulo")
        {
            String Salida=tbClave.getText();
            if(Salida.isEmpty()) {//verificacion si esta vacio
            JOptionPane.showMessageDialog(this, "¡No se ingreso clave de busqueda", "Advertencia", JOptionPane.WARNING_MESSAGE);
            return;
            }
            if(Salida.length()<50)
            {
            Salida=String.format("%-50s", Salida);
            }
            if((Titulo.Buscar(Salida))==(null))
            {
                JOptionPane.showMessageDialog(this, "No existe la clave ingresada en el arbol de Titulos", "Información", JOptionPane.INFORMATION_MESSAGE);
                return;
            }
            else
            tbSalidaClave.setText((String)Titulo.Buscar(Salida));
        }
    }//GEN-LAST:event_btBuscarActionPerformed

    private void cbBuquedaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbBuquedaActionPerformed
        // Cambia el estado de un texfiel dependedio del valor de busqueda
        //tbSalidaClave.setText(Nodo);
        String Seleccionado=(String)cbBuqueda.getSelectedItem();
        if(Seleccionado=="Arbol por Codigo")
        {
            lbClaveArbol.setText("codigo"); 
        }
        if(Seleccionado=="Arbol por Autor")
        {
            lbClaveArbol.setText("autor"); 
        }
        if(Seleccionado=="Arbol por Titulo")
        {
            lbClaveArbol.setText("titulo"); 
        }
        
    }//GEN-LAST:event_cbBuquedaActionPerformed

    private void cbTipoArbolRangoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbTipoArbolRangoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbTipoArbolRangoActionPerformed

    private void btnBuscarRangoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarRangoActionPerformed
        // Busca elementos asociados al arbol en un rango que esta entre 2 claves de busqueda
        String Seleccionado=(String)cbTipoArbolRango.getSelectedItem();
        if(Nodo.isEmpty())//validacion de que el texbox no este vacio
        {
             JOptionPane.showMessageDialog(this, "¡Se debe crear los arboles primero!", "Advertencia", JOptionPane.WARNING_MESSAGE);
            return;
        }
        if(Seleccionado=="Arbol por Codigo")
        {
            String Inicio=tbInicio.getText();//asignacion de la clave incial
            String Final=tbFinal.getText();//asignacion de la clave final
            if(Inicio.isEmpty()) {//verificacion si esta vacio
            JOptionPane.showMessageDialog(this, "¡No se ingreso clave de Inicio", "Advertencia", JOptionPane.WARNING_MESSAGE);
            return;
            }
            if(Final.isEmpty()) {//verificacion si esta vacio
            JOptionPane.showMessageDialog(this, "¡No se ingreso clave de Final", "Advertencia", JOptionPane.WARNING_MESSAGE);
            return;
            }
            if(Inicio.length()<5)
            {
            Inicio=String.format("%-5s", Inicio);
            }
            if(Final.length()<5)
            {
            Final=String.format("%-5s", Final);//adecuacion del formato
            }
            if((Codigo.Buscar(Inicio))==(null))//validacion de que la clave inicial exista
            {
                JOptionPane.showMessageDialog(this, "No existe la clave de inicio ingresada en el arbol de Codigos", "Información", JOptionPane.INFORMATION_MESSAGE);
                return;
            }
            else
            {
                if((Codigo.Buscar(Final))==(null))//validacion de que la clave final exista
                {
                    JOptionPane.showMessageDialog(this, "No existe la clave Final ingresada en el arbol de Codigos", "Información", JOptionPane.INFORMATION_MESSAGE);
                    return;
                }
                else
                {
                    
                    taSalidaRango.setText((Codigo.buscarRango(Inicio, ArbolBMas.NormaRango.INCLUSIVO, Final, ArbolBMas.NormaRango.INCLUSIVO).toString()));
                }
            }
            
            
            
            
        }
        if(Seleccionado=="Arbol por Autor")// se repite para cada opcion del combobox
        {
            String Inicio=tbInicio.getText();
            String Final=tbFinal.getText();
            if(Inicio.isEmpty()) {//verificacion si esta vacio
            JOptionPane.showMessageDialog(this, "¡No se ingreso clave de Inicio", "Advertencia", JOptionPane.WARNING_MESSAGE);
            return;
            }
            if(Final.isEmpty()) {//verificacion si esta vacio
            JOptionPane.showMessageDialog(this, "¡No se ingreso clave de Final", "Advertencia", JOptionPane.WARNING_MESSAGE);
            return;
            }
            if(Inicio.length()<30)
            {
            Inicio=String.format("%-30s", Inicio);
            }
            if(Final.length()<30)
            {
            Final=String.format("%-30s", Final);
            }
            if((Autor.Buscar(Inicio))==(null))
            {
                JOptionPane.showMessageDialog(this, "No existe la clave de inicio ingresada en el arbol de Autores", "Información", JOptionPane.INFORMATION_MESSAGE);
                return;
            }
            else
            {
                if((Autor.Buscar(Final))==(null))
                {
                    JOptionPane.showMessageDialog(this, "No existe la clave Final ingresada en el arbol de Autores", "Información", JOptionPane.INFORMATION_MESSAGE);
                    return;
                }
                else
                {
                    
                    taSalidaRango.setText((Autor.buscarRango(Inicio, ArbolBMas.NormaRango.INCLUSIVO, Final, ArbolBMas.NormaRango.INCLUSIVO).toString()));
                }
            }
        }
        if(Seleccionado=="Arbol por Titulo")
        {
           String Inicio=tbInicio.getText();
            String Final=tbFinal.getText();
            if(Inicio.isEmpty()) {//verificacion si esta vacio
            JOptionPane.showMessageDialog(this, "¡No se ingreso clave de Inicio", "Advertencia", JOptionPane.WARNING_MESSAGE);
            return;
            }
            if(Final.isEmpty()) {//verificacion si esta vacio
            JOptionPane.showMessageDialog(this, "¡No se ingreso clave de Final", "Advertencia", JOptionPane.WARNING_MESSAGE);
            return;
            }
            if(Inicio.length()<50)
            {
            Inicio=String.format("%-50s", Inicio);
            }
            if(Final.length()<50)
            {
            Final=String.format("%-50s", Final);
            }
            if((Titulo.Buscar(Inicio))==(null))
            {
                JOptionPane.showMessageDialog(this, "No existe la clave de inicio ingresada en el arbol de Titulos", "Información", JOptionPane.INFORMATION_MESSAGE);
                return;
            }
            else
            {
                if((Titulo.Buscar(Final))==(null))
                {
                    JOptionPane.showMessageDialog(this, "No existe la clave Final ingresada en el arbol de Titulos", "Información", JOptionPane.INFORMATION_MESSAGE);
                    return;
                }
                else
                {
                    
                    taSalidaRango.setText((Titulo.buscarRango(Inicio, ArbolBMas.NormaRango.INCLUSIVO, Final, ArbolBMas.NormaRango.INCLUSIVO).toString()));
                }
            }
        }
    }//GEN-LAST:event_btnBuscarRangoActionPerformed

    private void txtValorNodoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtValorNodoFocusGained
        // TODO add your handling code here:
        txtValorNodo.selectAll();
    }//GEN-LAST:event_txtValorNodoFocusGained

    private void tbClaveFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tbClaveFocusGained
        // TODO add your handling code here:
        tbClave.selectAll();
    }//GEN-LAST:event_tbClaveFocusGained

    private void tbInicioFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tbInicioFocusGained
        // TODO add your handling code here:
        tbInicio.selectAll();
    }//GEN-LAST:event_tbInicioFocusGained

    private void tbFinalFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tbFinalFocusGained
        // TODO add your handling code here:
        tbFinal.selectAll();
    }//GEN-LAST:event_tbFinalFocusGained

    private void txtValorNodoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtValorNodoKeyTyped
        // TODO add your handling code here:
        char validar=evt.getKeyChar();
        if(Character.isLetter(validar))
        {
            getToolkit().beep();
            evt.consume();
             JOptionPane.showMessageDialog(this, "Ingrese solo numeros", "Alerta", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_txtValorNodoKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Arboles.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Arboles.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Arboles.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Arboles.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Arboles().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btBuscar;
    private javax.swing.JButton btnBuscarRango;
    private javax.swing.JButton btnCrearArboles;
    private javax.swing.JComboBox<String> cbBuqueda;
    private javax.swing.JComboBox<String> cbTipoArbolRango;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JLabel lbClaveArbol;
    private javax.swing.JTextArea taArbolAutor;
    private javax.swing.JTextArea taArbolCodigo;
    private javax.swing.JTextArea taArbolTitulo;
    private javax.swing.JTextArea taSalidaRango;
    private javax.swing.JTextField tbClave;
    private javax.swing.JTextField tbFinal;
    private javax.swing.JTextField tbInicio;
    private javax.swing.JTextField tbSalidaClave;
    private javax.swing.JTextField txtValorNodo;
    // End of variables declaration//GEN-END:variables
}
