/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Control.AccesoAleatorio;
import Modelo.Libro;
import java.io.File;
import java.io.IOException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author usurio
 */
public class Modificar extends javax.swing.JFrame {
    DefaultTableModel M=new DefaultTableModel();
    /**
     * Creates new form Modificar
     */
    public Modificar() {
        initComponents();
        
        String[] titulos=new String[]{"Ind","CodLibro","Titulo","Autor","Año","Estado"};
        M.setColumnIdentifiers(titulos);
        
        TablaModificacion.setModel(M);
        
        try {
            AccesoAleatorio.crearFileLibro( new File("Libro.dat") );
            for(int i=0; i<AccesoAleatorio.getNumeroRegistros();i++){//recorrido pero solo en registro donde su estado sea 0
                Libro A=AccesoAleatorio.getLibro(i);//Encontrar libro a eliminar, i su posicion
                if(A.getEstado()==0)
                {
                     M.addRow(new Object[]{i,A.getCodLibro(),A.getTitulo(),A.getAutor(),A.getAño(),A.getEstado()});
                }
              
            } 
            
        } catch(IOException e) {
            JOptionPane.showMessageDialog(this, "Error en la búsqueda de registros.", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        btModificar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        TablaModificacion = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        mCodLibro = new javax.swing.JTextField();
        mTitulo = new javax.swing.JTextField();
        mAutor = new javax.swing.JTextField();
        mAño = new javax.swing.JTextField();
        btCancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        btModificar.setText("Modificar");
        btModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btModificarActionPerformed(evt);
            }
        });

        TablaModificacion.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        TablaModificacion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TablaModificacionMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(TablaModificacion);

        jLabel1.setText("CodLibro:");

        jLabel2.setText("Titulo:");

        jLabel3.setText("Autor:");

        jLabel4.setText("Año:");

        btCancelar.setText("Cancelar");
        btCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 661, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(mAño, javax.swing.GroupLayout.DEFAULT_SIZE, 199, Short.MAX_VALUE)
                            .addComponent(mAutor)
                            .addComponent(mTitulo)
                            .addComponent(mCodLibro))
                        .addGap(107, 107, 107)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btModificar)
                            .addComponent(btCancelar))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(mCodLibro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(mTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(btModificar)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(mAutor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(btCancelar)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(mAño, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 118, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 31, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btModificarActionPerformed
        // TODO add your handling code here:
        String CodLibro = mCodLibro.getText().trim();//asigacion del txt
        if(CodLibro.isEmpty()) {//verificacion si esta vacio
            JOptionPane.showMessageDialog(this, "¡No se ingreso el Codigo del libro", "Advertencia", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        if(CodLibro.length()<5)
        {
            CodLibro=String.format("%-5s", CodLibro);
        }
         
        String Titulo = mTitulo.getText().trim();
        if(Titulo.isEmpty()) {
            JOptionPane.showMessageDialog(this, "¡No se ingreso Titulo del libro", "Advertencia", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        if(Titulo.length()<50)
        {
            Titulo=String.format("%-50s", Titulo);
        }
           
           
        String Autor = mAutor.getText().trim();
        if(Autor.isEmpty()) {
            JOptionPane.showMessageDialog(this, "¡No se ingreso Autor del libro", "Advertencia", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
         if(Autor.length()<30)
        {
            Autor=String.format("%-5s", Autor);
        }
         
        String _Año = mAño.getText().trim();
        if(_Año.isEmpty()) {
            JOptionPane.showMessageDialog(this, "¡No se ingreso Año del libro", "Advertencia", JOptionPane.WARNING_MESSAGE);
            return;
        }
        int Año;
        
        try{
            Año=Integer.parseInt(_Año);//conversion a int del año
            
            
        }catch(NumberFormatException nfe)
        {
             JOptionPane.showMessageDialog(this, "Debe ser ingresar un numero entero para el año.", "Advertencia", JOptionPane.WARNING_MESSAGE);             
             return;
        }
        
        int fsel = TablaModificacion.getSelectedRow();
        
        
        int Ubicacion=Integer.parseInt(TablaModificacion.getValueAt(fsel, 0).toString());
        int Estado=Integer.parseInt(TablaModificacion.getValueAt(fsel, 5).toString());
        
        try {
            AccesoAleatorio.crearFileLibro( new File("Libro.dat") );
            AccesoAleatorio.setLibro(Ubicacion,new Libro(CodLibro,Titulo,Autor,Año,Estado));//agregar el libro en la ulrima poscion
            AccesoAleatorio.cerrar();
            JOptionPane.showMessageDialog(this, "El registro se realizó correctamente.", "Notificación", JOptionPane.INFORMATION_MESSAGE);
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(this, "Error en la escritura de datos.", "Error", JOptionPane.ERROR_MESSAGE);
        }
       
        
        
        this.setVisible(false);
    }//GEN-LAST:event_btModificarActionPerformed

    private void TablaModificacionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TablaModificacionMouseClicked
        // TODO add your handling code here:
         int fsel = TablaModificacion.getSelectedRow();
        
        M=(DefaultTableModel) TablaModificacion.getModel();
        String CodLibro,Titulo,Autor,Año,Estado;
        CodLibro=TablaModificacion.getValueAt(fsel, 1).toString();
        Titulo=TablaModificacion.getValueAt(fsel, 2).toString();
        Autor=TablaModificacion.getValueAt(fsel, 3).toString();
        Año=TablaModificacion.getValueAt(fsel, 4).toString();
        Estado=TablaModificacion.getValueAt(fsel, 5).toString();
        
        mCodLibro.setText(CodLibro);
        mTitulo.setText(Titulo);
        mAutor.setText(Autor);
        mAño.setText(Año);
    }//GEN-LAST:event_TablaModificacionMouseClicked

    private void btCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCancelarActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
    }//GEN-LAST:event_btCancelarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Modificar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Modificar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Modificar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Modificar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Modificar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable TablaModificacion;
    private javax.swing.JButton btCancelar;
    private javax.swing.JButton btModificar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField mAutor;
    private javax.swing.JTextField mAño;
    private javax.swing.JTextField mCodLibro;
    private javax.swing.JTextField mTitulo;
    // End of variables declaration//GEN-END:variables
}
